name: decompiler
services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    volumes:
      - ./api:/app
      - ./api/uploads:/tmp/uploads
      - ./api/decompiled:/tmp/decompiled
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - app-network

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge